title: Modelos de evaluación de RED
author: Marlon Joaquin Gomez Arguello
description: Portafolio de Evaluación de Recursos Educativos Digitales en Ingeniería de Producción.
# Se omite el theme para control total sobre el HTML/CSS
